server:
  host: 0.0.0.0
  port: 8080
  mode: debug
  frontend_url: http://localhost:3000

database:
  host: 127.0.0.1
  port: 5432
  user: sub2api
  password: sub2api
  dbname: sub2api
  sslmode: disable

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0

jwt:
  secret: "dev-secret-change-in-production-abc123xyz"
  expire_hour: 168

run_mode: simple

log:
  level: debug
  format: console
  output:
    to_stdout: true