// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/mediatask"
)

// MediaTask is the model entity for the MediaTask schema.
type MediaTask struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 对用户暴露的唯一任务 ID，如 med_xxx / img_xxx / vid_xxx
	LocalID string `json:"local_id,omitempty"`
	// image / video / audio
	MediaKind string `json:"media_kind,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// 用户请求的统一模型名，如 seedance-2.5
	PublicModel string `json:"public_model,omitempty"`
	// model_mapping 翻译后上游实际模型名
	UpstreamModel string `json:"upstream_model,omitempty"`
	// 实际使用的上游 channel (Account) ID
	AccountID int64 `json:"account_id,omitempty"`
	// 上游返回的任务 ID
	UpstreamTaskID string `json:"upstream_task_id,omitempty"`
	// processing / succeeded / failed / cancelled
	Status string `json:"status,omitempty"`
	// Resolution holds the value of the "resolution" field.
	Resolution string `json:"resolution,omitempty"`
	// DurationSec holds the value of the "duration_sec" field.
	DurationSec int `json:"duration_sec,omitempty"`
	// 产物 URL（视频 / 图片 / 音频）
	MediaURL string `json:"media_url,omitempty"`
	// 多张产物 URL（图片 n>1 时全量落库，轮询接口据此返回 urls）
	MediaUrls []string `json:"media_urls,omitempty"`
	// ThumbnailURL holds the value of the "thumbnail_url" field.
	ThumbnailURL string `json:"thumbnail_url,omitempty"`
	// 原始请求快照，便于排障
	RequestBody map[string]interface{} `json:"request_body,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	// CostUsd holds the value of the "cost_usd" field.
	CostUsd float64 `json:"cost_usd,omitempty"`
	// 创建时预扣的估算费用，完成时用于多退少补
	ReservedCost *float64 `json:"reserved_cost,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt   *time.Time `json:"finished_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MediaTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mediatask.FieldMediaUrls, mediatask.FieldRequestBody:
			values[i] = new([]byte)
		case mediatask.FieldCostUsd, mediatask.FieldReservedCost:
			values[i] = new(sql.NullFloat64)
		case mediatask.FieldID, mediatask.FieldUserID, mediatask.FieldAPIKeyID, mediatask.FieldAccountID, mediatask.FieldDurationSec:
			values[i] = new(sql.NullInt64)
		case mediatask.FieldLocalID, mediatask.FieldMediaKind, mediatask.FieldPublicModel, mediatask.FieldUpstreamModel, mediatask.FieldUpstreamTaskID, mediatask.FieldStatus, mediatask.FieldResolution, mediatask.FieldMediaURL, mediatask.FieldThumbnailURL, mediatask.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case mediatask.FieldCreatedAt, mediatask.FieldUpdatedAt, mediatask.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MediaTask fields.
func (_m *MediaTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mediatask.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case mediatask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case mediatask.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case mediatask.FieldLocalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field local_id", values[i])
			} else if value.Valid {
				_m.LocalID = value.String
			}
		case mediatask.FieldMediaKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field media_kind", values[i])
			} else if value.Valid {
				_m.MediaKind = value.String
			}
		case mediatask.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case mediatask.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case mediatask.FieldPublicModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_model", values[i])
			} else if value.Valid {
				_m.PublicModel = value.String
			}
		case mediatask.FieldUpstreamModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model", values[i])
			} else if value.Valid {
				_m.UpstreamModel = value.String
			}
		case mediatask.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case mediatask.FieldUpstreamTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_task_id", values[i])
			} else if value.Valid {
				_m.UpstreamTaskID = value.String
			}
		case mediatask.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case mediatask.FieldResolution:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resolution", values[i])
			} else if value.Valid {
				_m.Resolution = value.String
			}
		case mediatask.FieldDurationSec:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_sec", values[i])
			} else if value.Valid {
				_m.DurationSec = int(value.Int64)
			}
		case mediatask.FieldMediaURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field media_url", values[i])
			} else if value.Valid {
				_m.MediaURL = value.String
			}
		case mediatask.FieldMediaUrls:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field media_urls", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.MediaUrls); err != nil {
					return fmt.Errorf("unmarshal field media_urls: %w", err)
				}
			}
		case mediatask.FieldThumbnailURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field thumbnail_url", values[i])
			} else if value.Valid {
				_m.ThumbnailURL = value.String
			}
		case mediatask.FieldRequestBody:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_body", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RequestBody); err != nil {
					return fmt.Errorf("unmarshal field request_body: %w", err)
				}
			}
		case mediatask.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case mediatask.FieldCostUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cost_usd", values[i])
			} else if value.Valid {
				_m.CostUsd = value.Float64
			}
		case mediatask.FieldReservedCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reserved_cost", values[i])
			} else if value.Valid {
				_m.ReservedCost = new(float64)
				*_m.ReservedCost = value.Float64
			}
		case mediatask.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MediaTask.
// This includes values selected through modifiers, order, etc.
func (_m *MediaTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MediaTask.
// Note that you need to call MediaTask.Unwrap() before calling this method if this MediaTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MediaTask) Update() *MediaTaskUpdateOne {
	return NewMediaTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MediaTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MediaTask) Unwrap() *MediaTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MediaTask is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MediaTask) String() string {
	var builder strings.Builder
	builder.WriteString("MediaTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("local_id=")
	builder.WriteString(_m.LocalID)
	builder.WriteString(", ")
	builder.WriteString("media_kind=")
	builder.WriteString(_m.MediaKind)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("public_model=")
	builder.WriteString(_m.PublicModel)
	builder.WriteString(", ")
	builder.WriteString("upstream_model=")
	builder.WriteString(_m.UpstreamModel)
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("upstream_task_id=")
	builder.WriteString(_m.UpstreamTaskID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("resolution=")
	builder.WriteString(_m.Resolution)
	builder.WriteString(", ")
	builder.WriteString("duration_sec=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationSec))
	builder.WriteString(", ")
	builder.WriteString("media_url=")
	builder.WriteString(_m.MediaURL)
	builder.WriteString(", ")
	builder.WriteString("media_urls=")
	builder.WriteString(fmt.Sprintf("%v", _m.MediaUrls))
	builder.WriteString(", ")
	builder.WriteString("thumbnail_url=")
	builder.WriteString(_m.ThumbnailURL)
	builder.WriteString(", ")
	builder.WriteString("request_body=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestBody))
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("cost_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.CostUsd))
	builder.WriteString(", ")
	if v := _m.ReservedCost; v != nil {
		builder.WriteString("reserved_cost=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// MediaTasks is a parsable slice of MediaTask.
type MediaTasks []*MediaTask
