// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/mediatask"
)

// MediaTaskCreate is the builder for creating a MediaTask entity.
type MediaTaskCreate struct {
	config
	mutation *MediaTaskMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *MediaTaskCreate) SetCreatedAt(v time.Time) *MediaTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MediaTaskCreate) SetNillableCreatedAt(v *time.Time) *MediaTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MediaTaskCreate) SetUpdatedAt(v time.Time) *MediaTaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MediaTaskCreate) SetNillableUpdatedAt(v *time.Time) *MediaTaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetLocalID sets the "local_id" field.
func (_c *MediaTaskCreate) SetLocalID(v string) *MediaTaskCreate {
	_c.mutation.SetLocalID(v)
	return _c
}

// SetMediaKind sets the "media_kind" field.
func (_c *MediaTaskCreate) SetMediaKind(v string) *MediaTaskCreate {
	_c.mutation.SetMediaKind(v)
	return _c
}

// SetNillableMediaKind sets the "media_kind" field if the given value is not nil.
func (_c *MediaTaskCreate) SetNillableMediaKind(v *string) *MediaTaskCreate {
	if v != nil {
		_c.SetMediaKind(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *MediaTaskCreate) SetUserID(v int64) *MediaTaskCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *MediaTaskCreate) SetAPIKeyID(v int64) *MediaTaskCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *MediaTaskCreate) SetNillableAPIKeyID(v *int64) *MediaTaskCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetPublicModel sets the "public_model" field.
func (_c *MediaTaskCreate) SetPublicModel(v string) *MediaTaskCreate {
	_c.mutation.SetPublicModel(v)
	return _c
}

// SetUpstreamModel sets the "upstream_model" field.
func (_c *MediaTaskCreate) SetUpstreamModel(v string) *MediaTaskCreate {
	_c.mutation.SetUpstreamModel(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *MediaTaskCreate) SetAccountID(v int64) *MediaTaskCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_c *MediaTaskCreate) SetUpstreamTaskID(v string) *MediaTaskCreate {
	_c.mutation.SetUpstreamTaskID(v)
	return _c
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_c *MediaTaskCreate) SetNillableUpstreamTaskID(v *string) *MediaTaskCreate {
	if v != nil {
		_c.SetUpstreamTaskID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *MediaTaskCreate) SetStatus(v string) *MediaTaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MediaTaskCreate) SetNillableStatus(v *string) *MediaTaskCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetResolution sets the "resolution" field.
func (_c *MediaTaskCreate) SetResolution(v string) *MediaTaskCreate {
	_c.mutation.SetResolution(v)
	return _c
}

// SetNillableResolution sets the "resolution" field if the given value is not nil.
func (_c *MediaTaskCreate) SetNillableResolution(v *string) *MediaTaskCreate {
	if v != nil {
		_c.SetResolution(*v)
	}
	return _c
}

// SetDurationSec sets the "duration_sec" field.
func (_c *MediaTaskCreate) SetDurationSec(v int) *MediaTaskCreate {
	_c.mutation.SetDurationSec(v)
	return _c
}

// SetNillableDurationSec sets the "duration_sec" field if the given value is not nil.
func (_c *MediaTaskCreate) SetNillableDurationSec(v *int) *MediaTaskCreate {
	if v != nil {
		_c.SetDurationSec(*v)
	}
	return _c
}

// SetMediaURL sets the "media_url" field.
func (_c *MediaTaskCreate) SetMediaURL(v string) *MediaTaskCreate {
	_c.mutation.SetMediaURL(v)
	return _c
}

// SetNillableMediaURL sets the "media_url" field if the given value is not nil.
func (_c *MediaTaskCreate) SetNillableMediaURL(v *string) *MediaTaskCreate {
	if v != nil {
		_c.SetMediaURL(*v)
	}
	return _c
}

// SetMediaUrls sets the "media_urls" field.
func (_c *MediaTaskCreate) SetMediaUrls(v []string) *MediaTaskCreate {
	_c.mutation.SetMediaUrls(v)
	return _c
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_c *MediaTaskCreate) SetThumbnailURL(v string) *MediaTaskCreate {
	_c.mutation.SetThumbnailURL(v)
	return _c
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_c *MediaTaskCreate) SetNillableThumbnailURL(v *string) *MediaTaskCreate {
	if v != nil {
		_c.SetThumbnailURL(*v)
	}
	return _c
}

// SetRequestBody sets the "request_body" field.
func (_c *MediaTaskCreate) SetRequestBody(v map[string]interface{}) *MediaTaskCreate {
	_c.mutation.SetRequestBody(v)
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *MediaTaskCreate) SetErrorMessage(v string) *MediaTaskCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *MediaTaskCreate) SetNillableErrorMessage(v *string) *MediaTaskCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetCostUsd sets the "cost_usd" field.
func (_c *MediaTaskCreate) SetCostUsd(v float64) *MediaTaskCreate {
	_c.mutation.SetCostUsd(v)
	return _c
}

// SetNillableCostUsd sets the "cost_usd" field if the given value is not nil.
func (_c *MediaTaskCreate) SetNillableCostUsd(v *float64) *MediaTaskCreate {
	if v != nil {
		_c.SetCostUsd(*v)
	}
	return _c
}

// SetReservedCost sets the "reserved_cost" field.
func (_c *MediaTaskCreate) SetReservedCost(v float64) *MediaTaskCreate {
	_c.mutation.SetReservedCost(v)
	return _c
}

// SetNillableReservedCost sets the "reserved_cost" field if the given value is not nil.
func (_c *MediaTaskCreate) SetNillableReservedCost(v *float64) *MediaTaskCreate {
	if v != nil {
		_c.SetReservedCost(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *MediaTaskCreate) SetFinishedAt(v time.Time) *MediaTaskCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *MediaTaskCreate) SetNillableFinishedAt(v *time.Time) *MediaTaskCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// Mutation returns the MediaTaskMutation object of the builder.
func (_c *MediaTaskCreate) Mutation() *MediaTaskMutation {
	return _c.mutation
}

// Save creates the MediaTask in the database.
func (_c *MediaTaskCreate) Save(ctx context.Context) (*MediaTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MediaTaskCreate) SaveX(ctx context.Context) *MediaTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MediaTaskCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mediatask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := mediatask.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.MediaKind(); !ok {
		v := mediatask.DefaultMediaKind
		_c.mutation.SetMediaKind(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := mediatask.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CostUsd(); !ok {
		v := mediatask.DefaultCostUsd
		_c.mutation.SetCostUsd(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MediaTaskCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MediaTask.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MediaTask.updated_at"`)}
	}
	if _, ok := _c.mutation.LocalID(); !ok {
		return &ValidationError{Name: "local_id", err: errors.New(`ent: missing required field "MediaTask.local_id"`)}
	}
	if v, ok := _c.mutation.LocalID(); ok {
		if err := mediatask.LocalIDValidator(v); err != nil {
			return &ValidationError{Name: "local_id", err: fmt.Errorf(`ent: validator failed for field "MediaTask.local_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MediaKind(); !ok {
		return &ValidationError{Name: "media_kind", err: errors.New(`ent: missing required field "MediaTask.media_kind"`)}
	}
	if v, ok := _c.mutation.MediaKind(); ok {
		if err := mediatask.MediaKindValidator(v); err != nil {
			return &ValidationError{Name: "media_kind", err: fmt.Errorf(`ent: validator failed for field "MediaTask.media_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "MediaTask.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := mediatask.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "MediaTask.user_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.APIKeyID(); ok {
		if err := mediatask.APIKeyIDValidator(v); err != nil {
			return &ValidationError{Name: "api_key_id", err: fmt.Errorf(`ent: validator failed for field "MediaTask.api_key_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PublicModel(); !ok {
		return &ValidationError{Name: "public_model", err: errors.New(`ent: missing required field "MediaTask.public_model"`)}
	}
	if v, ok := _c.mutation.PublicModel(); ok {
		if err := mediatask.PublicModelValidator(v); err != nil {
			return &ValidationError{Name: "public_model", err: fmt.Errorf(`ent: validator failed for field "MediaTask.public_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpstreamModel(); !ok {
		return &ValidationError{Name: "upstream_model", err: errors.New(`ent: missing required field "MediaTask.upstream_model"`)}
	}
	if v, ok := _c.mutation.UpstreamModel(); ok {
		if err := mediatask.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "MediaTask.upstream_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "MediaTask.account_id"`)}
	}
	if v, ok := _c.mutation.AccountID(); ok {
		if err := mediatask.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "MediaTask.account_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UpstreamTaskID(); ok {
		if err := mediatask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "MediaTask.upstream_task_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MediaTask.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := mediatask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MediaTask.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Resolution(); ok {
		if err := mediatask.ResolutionValidator(v); err != nil {
			return &ValidationError{Name: "resolution", err: fmt.Errorf(`ent: validator failed for field "MediaTask.resolution": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DurationSec(); ok {
		if err := mediatask.DurationSecValidator(v); err != nil {
			return &ValidationError{Name: "duration_sec", err: fmt.Errorf(`ent: validator failed for field "MediaTask.duration_sec": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CostUsd(); !ok {
		return &ValidationError{Name: "cost_usd", err: errors.New(`ent: missing required field "MediaTask.cost_usd"`)}
	}
	return nil
}

func (_c *MediaTaskCreate) sqlSave(ctx context.Context) (*MediaTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MediaTaskCreate) createSpec() (*MediaTask, *sqlgraph.CreateSpec) {
	var (
		_node = &MediaTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mediatask.Table, sqlgraph.NewFieldSpec(mediatask.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mediatask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(mediatask.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.LocalID(); ok {
		_spec.SetField(mediatask.FieldLocalID, field.TypeString, value)
		_node.LocalID = value
	}
	if value, ok := _c.mutation.MediaKind(); ok {
		_spec.SetField(mediatask.FieldMediaKind, field.TypeString, value)
		_node.MediaKind = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(mediatask.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(mediatask.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.PublicModel(); ok {
		_spec.SetField(mediatask.FieldPublicModel, field.TypeString, value)
		_node.PublicModel = value
	}
	if value, ok := _c.mutation.UpstreamModel(); ok {
		_spec.SetField(mediatask.FieldUpstreamModel, field.TypeString, value)
		_node.UpstreamModel = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(mediatask.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.UpstreamTaskID(); ok {
		_spec.SetField(mediatask.FieldUpstreamTaskID, field.TypeString, value)
		_node.UpstreamTaskID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(mediatask.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Resolution(); ok {
		_spec.SetField(mediatask.FieldResolution, field.TypeString, value)
		_node.Resolution = value
	}
	if value, ok := _c.mutation.DurationSec(); ok {
		_spec.SetField(mediatask.FieldDurationSec, field.TypeInt, value)
		_node.DurationSec = value
	}
	if value, ok := _c.mutation.MediaURL(); ok {
		_spec.SetField(mediatask.FieldMediaURL, field.TypeString, value)
		_node.MediaURL = value
	}
	if value, ok := _c.mutation.MediaUrls(); ok {
		_spec.SetField(mediatask.FieldMediaUrls, field.TypeJSON, value)
		_node.MediaUrls = value
	}
	if value, ok := _c.mutation.ThumbnailURL(); ok {
		_spec.SetField(mediatask.FieldThumbnailURL, field.TypeString, value)
		_node.ThumbnailURL = value
	}
	if value, ok := _c.mutation.RequestBody(); ok {
		_spec.SetField(mediatask.FieldRequestBody, field.TypeJSON, value)
		_node.RequestBody = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(mediatask.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.CostUsd(); ok {
		_spec.SetField(mediatask.FieldCostUsd, field.TypeFloat64, value)
		_node.CostUsd = value
	}
	if value, ok := _c.mutation.ReservedCost(); ok {
		_spec.SetField(mediatask.FieldReservedCost, field.TypeFloat64, value)
		_node.ReservedCost = &value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(mediatask.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MediaTask.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MediaTaskUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MediaTaskCreate) OnConflict(opts ...sql.ConflictOption) *MediaTaskUpsertOne {
	_c.conflict = opts
	return &MediaTaskUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MediaTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MediaTaskCreate) OnConflictColumns(columns ...string) *MediaTaskUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MediaTaskUpsertOne{
		create: _c,
	}
}

type (
	// MediaTaskUpsertOne is the builder for "upsert"-ing
	//  one MediaTask node.
	MediaTaskUpsertOne struct {
		create *MediaTaskCreate
	}

	// MediaTaskUpsert is the "OnConflict" setter.
	MediaTaskUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *MediaTaskUpsert) SetUpdatedAt(v time.Time) *MediaTaskUpsert {
	u.Set(mediatask.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MediaTaskUpsert) UpdateUpdatedAt() *MediaTaskUpsert {
	u.SetExcluded(mediatask.FieldUpdatedAt)
	return u
}

// SetLocalID sets the "local_id" field.
func (u *MediaTaskUpsert) SetLocalID(v string) *MediaTaskUpsert {
	u.Set(mediatask.FieldLocalID, v)
	return u
}

// UpdateLocalID sets the "local_id" field to the value that was provided on create.
func (u *MediaTaskUpsert) UpdateLocalID() *MediaTaskUpsert {
	u.SetExcluded(mediatask.FieldLocalID)
	return u
}

// SetMediaKind sets the "media_kind" field.
func (u *MediaTaskUpsert) SetMediaKind(v string) *MediaTaskUpsert {
	u.Set(mediatask.FieldMediaKind, v)
	return u
}

// UpdateMediaKind sets the "media_kind" field to the value that was provided on create.
func (u *MediaTaskUpsert) UpdateMediaKind() *MediaTaskUpsert {
	u.SetExcluded(mediatask.FieldMediaKind)
	return u
}

// SetUserID sets the "user_id" field.
func (u *MediaTaskUpsert) SetUserID(v int64) *MediaTaskUpsert {
	u.Set(mediatask.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *MediaTaskUpsert) UpdateUserID() *MediaTaskUpsert {
	u.SetExcluded(mediatask.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *MediaTaskUpsert) AddUserID(v int64) *MediaTaskUpsert {
	u.Add(mediatask.FieldUserID, v)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *MediaTaskUpsert) SetAPIKeyID(v int64) *MediaTaskUpsert {
	u.Set(mediatask.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *MediaTaskUpsert) UpdateAPIKeyID() *MediaTaskUpsert {
	u.SetExcluded(mediatask.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *MediaTaskUpsert) AddAPIKeyID(v int64) *MediaTaskUpsert {
	u.Add(mediatask.FieldAPIKeyID, v)
	return u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *MediaTaskUpsert) ClearAPIKeyID() *MediaTaskUpsert {
	u.SetNull(mediatask.FieldAPIKeyID)
	return u
}

// SetPublicModel sets the "public_model" field.
func (u *MediaTaskUpsert) SetPublicModel(v string) *MediaTaskUpsert {
	u.Set(mediatask.FieldPublicModel, v)
	return u
}

// UpdatePublicModel sets the "public_model" field to the value that was provided on create.
func (u *MediaTaskUpsert) UpdatePublicModel() *MediaTaskUpsert {
	u.SetExcluded(mediatask.FieldPublicModel)
	return u
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *MediaTaskUpsert) SetUpstreamModel(v string) *MediaTaskUpsert {
	u.Set(mediatask.FieldUpstreamModel, v)
	return u
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *MediaTaskUpsert) UpdateUpstreamModel() *MediaTaskUpsert {
	u.SetExcluded(mediatask.FieldUpstreamModel)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *MediaTaskUpsert) SetAccountID(v int64) *MediaTaskUpsert {
	u.Set(mediatask.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *MediaTaskUpsert) UpdateAccountID() *MediaTaskUpsert {
	u.SetExcluded(mediatask.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *MediaTaskUpsert) AddAccountID(v int64) *MediaTaskUpsert {
	u.Add(mediatask.FieldAccountID, v)
	return u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (u *MediaTaskUpsert) SetUpstreamTaskID(v string) *MediaTaskUpsert {
	u.Set(mediatask.FieldUpstreamTaskID, v)
	return u
}

// UpdateUpstreamTaskID sets the "upstream_task_id" field to the value that was provided on create.
func (u *MediaTaskUpsert) UpdateUpstreamTaskID() *MediaTaskUpsert {
	u.SetExcluded(mediatask.FieldUpstreamTaskID)
	return u
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (u *MediaTaskUpsert) ClearUpstreamTaskID() *MediaTaskUpsert {
	u.SetNull(mediatask.FieldUpstreamTaskID)
	return u
}

// SetStatus sets the "status" field.
func (u *MediaTaskUpsert) SetStatus(v string) *MediaTaskUpsert {
	u.Set(mediatask.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MediaTaskUpsert) UpdateStatus() *MediaTaskUpsert {
	u.SetExcluded(mediatask.FieldStatus)
	return u
}

// SetResolution sets the "resolution" field.
func (u *MediaTaskUpsert) SetResolution(v string) *MediaTaskUpsert {
	u.Set(mediatask.FieldResolution, v)
	return u
}

// UpdateResolution sets the "resolution" field to the value that was provided on create.
func (u *MediaTaskUpsert) UpdateResolution() *MediaTaskUpsert {
	u.SetExcluded(mediatask.FieldResolution)
	return u
}

// ClearResolution clears the value of the "resolution" field.
func (u *MediaTaskUpsert) ClearResolution() *MediaTaskUpsert {
	u.SetNull(mediatask.FieldResolution)
	return u
}

// SetDurationSec sets the "duration_sec" field.
func (u *MediaTaskUpsert) SetDurationSec(v int) *MediaTaskUpsert {
	u.Set(mediatask.FieldDurationSec, v)
	return u
}

// UpdateDurationSec sets the "duration_sec" field to the value that was provided on create.
func (u *MediaTaskUpsert) UpdateDurationSec() *MediaTaskUpsert {
	u.SetExcluded(mediatask.FieldDurationSec)
	return u
}

// AddDurationSec adds v to the "duration_sec" field.
func (u *MediaTaskUpsert) AddDurationSec(v int) *MediaTaskUpsert {
	u.Add(mediatask.FieldDurationSec, v)
	return u
}

// ClearDurationSec clears the value of the "duration_sec" field.
func (u *MediaTaskUpsert) ClearDurationSec() *MediaTaskUpsert {
	u.SetNull(mediatask.FieldDurationSec)
	return u
}

// SetMediaURL sets the "media_url" field.
func (u *MediaTaskUpsert) SetMediaURL(v string) *MediaTaskUpsert {
	u.Set(mediatask.FieldMediaURL, v)
	return u
}

// UpdateMediaURL sets the "media_url" field to the value that was provided on create.
func (u *MediaTaskUpsert) UpdateMediaURL() *MediaTaskUpsert {
	u.SetExcluded(mediatask.FieldMediaURL)
	return u
}

// ClearMediaURL clears the value of the "media_url" field.
func (u *MediaTaskUpsert) ClearMediaURL() *MediaTaskUpsert {
	u.SetNull(mediatask.FieldMediaURL)
	return u
}

// SetMediaUrls sets the "media_urls" field.
func (u *MediaTaskUpsert) SetMediaUrls(v []string) *MediaTaskUpsert {
	u.Set(mediatask.FieldMediaUrls, v)
	return u
}

// UpdateMediaUrls sets the "media_urls" field to the value that was provided on create.
func (u *MediaTaskUpsert) UpdateMediaUrls() *MediaTaskUpsert {
	u.SetExcluded(mediatask.FieldMediaUrls)
	return u
}

// ClearMediaUrls clears the value of the "media_urls" field.
func (u *MediaTaskUpsert) ClearMediaUrls() *MediaTaskUpsert {
	u.SetNull(mediatask.FieldMediaUrls)
	return u
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (u *MediaTaskUpsert) SetThumbnailURL(v string) *MediaTaskUpsert {
	u.Set(mediatask.FieldThumbnailURL, v)
	return u
}

// UpdateThumbnailURL sets the "thumbnail_url" field to the value that was provided on create.
func (u *MediaTaskUpsert) UpdateThumbnailURL() *MediaTaskUpsert {
	u.SetExcluded(mediatask.FieldThumbnailURL)
	return u
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (u *MediaTaskUpsert) ClearThumbnailURL() *MediaTaskUpsert {
	u.SetNull(mediatask.FieldThumbnailURL)
	return u
}

// SetRequestBody sets the "request_body" field.
func (u *MediaTaskUpsert) SetRequestBody(v map[string]interface{}) *MediaTaskUpsert {
	u.Set(mediatask.FieldRequestBody, v)
	return u
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *MediaTaskUpsert) UpdateRequestBody() *MediaTaskUpsert {
	u.SetExcluded(mediatask.FieldRequestBody)
	return u
}

// ClearRequestBody clears the value of the "request_body" field.
func (u *MediaTaskUpsert) ClearRequestBody() *MediaTaskUpsert {
	u.SetNull(mediatask.FieldRequestBody)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *MediaTaskUpsert) SetErrorMessage(v string) *MediaTaskUpsert {
	u.Set(mediatask.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *MediaTaskUpsert) UpdateErrorMessage() *MediaTaskUpsert {
	u.SetExcluded(mediatask.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *MediaTaskUpsert) ClearErrorMessage() *MediaTaskUpsert {
	u.SetNull(mediatask.FieldErrorMessage)
	return u
}

// SetCostUsd sets the "cost_usd" field.
func (u *MediaTaskUpsert) SetCostUsd(v float64) *MediaTaskUpsert {
	u.Set(mediatask.FieldCostUsd, v)
	return u
}

// UpdateCostUsd sets the "cost_usd" field to the value that was provided on create.
func (u *MediaTaskUpsert) UpdateCostUsd() *MediaTaskUpsert {
	u.SetExcluded(mediatask.FieldCostUsd)
	return u
}

// AddCostUsd adds v to the "cost_usd" field.
func (u *MediaTaskUpsert) AddCostUsd(v float64) *MediaTaskUpsert {
	u.Add(mediatask.FieldCostUsd, v)
	return u
}

// SetReservedCost sets the "reserved_cost" field.
func (u *MediaTaskUpsert) SetReservedCost(v float64) *MediaTaskUpsert {
	u.Set(mediatask.FieldReservedCost, v)
	return u
}

// UpdateReservedCost sets the "reserved_cost" field to the value that was provided on create.
func (u *MediaTaskUpsert) UpdateReservedCost() *MediaTaskUpsert {
	u.SetExcluded(mediatask.FieldReservedCost)
	return u
}

// AddReservedCost adds v to the "reserved_cost" field.
func (u *MediaTaskUpsert) AddReservedCost(v float64) *MediaTaskUpsert {
	u.Add(mediatask.FieldReservedCost, v)
	return u
}

// ClearReservedCost clears the value of the "reserved_cost" field.
func (u *MediaTaskUpsert) ClearReservedCost() *MediaTaskUpsert {
	u.SetNull(mediatask.FieldReservedCost)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *MediaTaskUpsert) SetFinishedAt(v time.Time) *MediaTaskUpsert {
	u.Set(mediatask.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *MediaTaskUpsert) UpdateFinishedAt() *MediaTaskUpsert {
	u.SetExcluded(mediatask.FieldFinishedAt)
	return u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *MediaTaskUpsert) ClearFinishedAt() *MediaTaskUpsert {
	u.SetNull(mediatask.FieldFinishedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.MediaTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MediaTaskUpsertOne) UpdateNewValues() *MediaTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(mediatask.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MediaTask.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MediaTaskUpsertOne) Ignore() *MediaTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MediaTaskUpsertOne) DoNothing() *MediaTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MediaTaskCreate.OnConflict
// documentation for more info.
func (u *MediaTaskUpsertOne) Update(set func(*MediaTaskUpsert)) *MediaTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MediaTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MediaTaskUpsertOne) SetUpdatedAt(v time.Time) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MediaTaskUpsertOne) UpdateUpdatedAt() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetLocalID sets the "local_id" field.
func (u *MediaTaskUpsertOne) SetLocalID(v string) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetLocalID(v)
	})
}

// UpdateLocalID sets the "local_id" field to the value that was provided on create.
func (u *MediaTaskUpsertOne) UpdateLocalID() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateLocalID()
	})
}

// SetMediaKind sets the "media_kind" field.
func (u *MediaTaskUpsertOne) SetMediaKind(v string) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetMediaKind(v)
	})
}

// UpdateMediaKind sets the "media_kind" field to the value that was provided on create.
func (u *MediaTaskUpsertOne) UpdateMediaKind() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateMediaKind()
	})
}

// SetUserID sets the "user_id" field.
func (u *MediaTaskUpsertOne) SetUserID(v int64) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *MediaTaskUpsertOne) AddUserID(v int64) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *MediaTaskUpsertOne) UpdateUserID() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *MediaTaskUpsertOne) SetAPIKeyID(v int64) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *MediaTaskUpsertOne) AddAPIKeyID(v int64) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *MediaTaskUpsertOne) UpdateAPIKeyID() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *MediaTaskUpsertOne) ClearAPIKeyID() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetPublicModel sets the "public_model" field.
func (u *MediaTaskUpsertOne) SetPublicModel(v string) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetPublicModel(v)
	})
}

// UpdatePublicModel sets the "public_model" field to the value that was provided on create.
func (u *MediaTaskUpsertOne) UpdatePublicModel() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdatePublicModel()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *MediaTaskUpsertOne) SetUpstreamModel(v string) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *MediaTaskUpsertOne) UpdateUpstreamModel() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetAccountID sets the "account_id" field.
func (u *MediaTaskUpsertOne) SetAccountID(v int64) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *MediaTaskUpsertOne) AddAccountID(v int64) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *MediaTaskUpsertOne) UpdateAccountID() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateAccountID()
	})
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (u *MediaTaskUpsertOne) SetUpstreamTaskID(v string) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetUpstreamTaskID(v)
	})
}

// UpdateUpstreamTaskID sets the "upstream_task_id" field to the value that was provided on create.
func (u *MediaTaskUpsertOne) UpdateUpstreamTaskID() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateUpstreamTaskID()
	})
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (u *MediaTaskUpsertOne) ClearUpstreamTaskID() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.ClearUpstreamTaskID()
	})
}

// SetStatus sets the "status" field.
func (u *MediaTaskUpsertOne) SetStatus(v string) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MediaTaskUpsertOne) UpdateStatus() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetResolution sets the "resolution" field.
func (u *MediaTaskUpsertOne) SetResolution(v string) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetResolution(v)
	})
}

// UpdateResolution sets the "resolution" field to the value that was provided on create.
func (u *MediaTaskUpsertOne) UpdateResolution() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateResolution()
	})
}

// ClearResolution clears the value of the "resolution" field.
func (u *MediaTaskUpsertOne) ClearResolution() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.ClearResolution()
	})
}

// SetDurationSec sets the "duration_sec" field.
func (u *MediaTaskUpsertOne) SetDurationSec(v int) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetDurationSec(v)
	})
}

// AddDurationSec adds v to the "duration_sec" field.
func (u *MediaTaskUpsertOne) AddDurationSec(v int) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.AddDurationSec(v)
	})
}

// UpdateDurationSec sets the "duration_sec" field to the value that was provided on create.
func (u *MediaTaskUpsertOne) UpdateDurationSec() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateDurationSec()
	})
}

// ClearDurationSec clears the value of the "duration_sec" field.
func (u *MediaTaskUpsertOne) ClearDurationSec() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.ClearDurationSec()
	})
}

// SetMediaURL sets the "media_url" field.
func (u *MediaTaskUpsertOne) SetMediaURL(v string) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetMediaURL(v)
	})
}

// UpdateMediaURL sets the "media_url" field to the value that was provided on create.
func (u *MediaTaskUpsertOne) UpdateMediaURL() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateMediaURL()
	})
}

// ClearMediaURL clears the value of the "media_url" field.
func (u *MediaTaskUpsertOne) ClearMediaURL() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.ClearMediaURL()
	})
}

// SetMediaUrls sets the "media_urls" field.
func (u *MediaTaskUpsertOne) SetMediaUrls(v []string) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetMediaUrls(v)
	})
}

// UpdateMediaUrls sets the "media_urls" field to the value that was provided on create.
func (u *MediaTaskUpsertOne) UpdateMediaUrls() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateMediaUrls()
	})
}

// ClearMediaUrls clears the value of the "media_urls" field.
func (u *MediaTaskUpsertOne) ClearMediaUrls() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.ClearMediaUrls()
	})
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (u *MediaTaskUpsertOne) SetThumbnailURL(v string) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetThumbnailURL(v)
	})
}

// UpdateThumbnailURL sets the "thumbnail_url" field to the value that was provided on create.
func (u *MediaTaskUpsertOne) UpdateThumbnailURL() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateThumbnailURL()
	})
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (u *MediaTaskUpsertOne) ClearThumbnailURL() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.ClearThumbnailURL()
	})
}

// SetRequestBody sets the "request_body" field.
func (u *MediaTaskUpsertOne) SetRequestBody(v map[string]interface{}) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetRequestBody(v)
	})
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *MediaTaskUpsertOne) UpdateRequestBody() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateRequestBody()
	})
}

// ClearRequestBody clears the value of the "request_body" field.
func (u *MediaTaskUpsertOne) ClearRequestBody() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.ClearRequestBody()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *MediaTaskUpsertOne) SetErrorMessage(v string) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *MediaTaskUpsertOne) UpdateErrorMessage() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *MediaTaskUpsertOne) ClearErrorMessage() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.ClearErrorMessage()
	})
}

// SetCostUsd sets the "cost_usd" field.
func (u *MediaTaskUpsertOne) SetCostUsd(v float64) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetCostUsd(v)
	})
}

// AddCostUsd adds v to the "cost_usd" field.
func (u *MediaTaskUpsertOne) AddCostUsd(v float64) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.AddCostUsd(v)
	})
}

// UpdateCostUsd sets the "cost_usd" field to the value that was provided on create.
func (u *MediaTaskUpsertOne) UpdateCostUsd() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateCostUsd()
	})
}

// SetReservedCost sets the "reserved_cost" field.
func (u *MediaTaskUpsertOne) SetReservedCost(v float64) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetReservedCost(v)
	})
}

// AddReservedCost adds v to the "reserved_cost" field.
func (u *MediaTaskUpsertOne) AddReservedCost(v float64) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.AddReservedCost(v)
	})
}

// UpdateReservedCost sets the "reserved_cost" field to the value that was provided on create.
func (u *MediaTaskUpsertOne) UpdateReservedCost() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateReservedCost()
	})
}

// ClearReservedCost clears the value of the "reserved_cost" field.
func (u *MediaTaskUpsertOne) ClearReservedCost() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.ClearReservedCost()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *MediaTaskUpsertOne) SetFinishedAt(v time.Time) *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *MediaTaskUpsertOne) UpdateFinishedAt() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *MediaTaskUpsertOne) ClearFinishedAt() *MediaTaskUpsertOne {
	return u.Update(func(s *MediaTaskUpsert) {
		s.ClearFinishedAt()
	})
}

// Exec executes the query.
func (u *MediaTaskUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MediaTaskCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MediaTaskUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MediaTaskUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MediaTaskUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MediaTaskCreateBulk is the builder for creating many MediaTask entities in bulk.
type MediaTaskCreateBulk struct {
	config
	err      error
	builders []*MediaTaskCreate
	conflict []sql.ConflictOption
}

// Save creates the MediaTask entities in the database.
func (_c *MediaTaskCreateBulk) Save(ctx context.Context) ([]*MediaTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MediaTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MediaTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MediaTaskCreateBulk) SaveX(ctx context.Context) []*MediaTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MediaTask.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MediaTaskUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MediaTaskCreateBulk) OnConflict(opts ...sql.ConflictOption) *MediaTaskUpsertBulk {
	_c.conflict = opts
	return &MediaTaskUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MediaTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MediaTaskCreateBulk) OnConflictColumns(columns ...string) *MediaTaskUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MediaTaskUpsertBulk{
		create: _c,
	}
}

// MediaTaskUpsertBulk is the builder for "upsert"-ing
// a bulk of MediaTask nodes.
type MediaTaskUpsertBulk struct {
	create *MediaTaskCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MediaTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MediaTaskUpsertBulk) UpdateNewValues() *MediaTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(mediatask.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MediaTask.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MediaTaskUpsertBulk) Ignore() *MediaTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MediaTaskUpsertBulk) DoNothing() *MediaTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MediaTaskCreateBulk.OnConflict
// documentation for more info.
func (u *MediaTaskUpsertBulk) Update(set func(*MediaTaskUpsert)) *MediaTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MediaTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MediaTaskUpsertBulk) SetUpdatedAt(v time.Time) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MediaTaskUpsertBulk) UpdateUpdatedAt() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetLocalID sets the "local_id" field.
func (u *MediaTaskUpsertBulk) SetLocalID(v string) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetLocalID(v)
	})
}

// UpdateLocalID sets the "local_id" field to the value that was provided on create.
func (u *MediaTaskUpsertBulk) UpdateLocalID() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateLocalID()
	})
}

// SetMediaKind sets the "media_kind" field.
func (u *MediaTaskUpsertBulk) SetMediaKind(v string) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetMediaKind(v)
	})
}

// UpdateMediaKind sets the "media_kind" field to the value that was provided on create.
func (u *MediaTaskUpsertBulk) UpdateMediaKind() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateMediaKind()
	})
}

// SetUserID sets the "user_id" field.
func (u *MediaTaskUpsertBulk) SetUserID(v int64) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *MediaTaskUpsertBulk) AddUserID(v int64) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *MediaTaskUpsertBulk) UpdateUserID() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *MediaTaskUpsertBulk) SetAPIKeyID(v int64) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *MediaTaskUpsertBulk) AddAPIKeyID(v int64) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *MediaTaskUpsertBulk) UpdateAPIKeyID() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *MediaTaskUpsertBulk) ClearAPIKeyID() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetPublicModel sets the "public_model" field.
func (u *MediaTaskUpsertBulk) SetPublicModel(v string) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetPublicModel(v)
	})
}

// UpdatePublicModel sets the "public_model" field to the value that was provided on create.
func (u *MediaTaskUpsertBulk) UpdatePublicModel() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdatePublicModel()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *MediaTaskUpsertBulk) SetUpstreamModel(v string) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *MediaTaskUpsertBulk) UpdateUpstreamModel() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetAccountID sets the "account_id" field.
func (u *MediaTaskUpsertBulk) SetAccountID(v int64) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *MediaTaskUpsertBulk) AddAccountID(v int64) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *MediaTaskUpsertBulk) UpdateAccountID() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateAccountID()
	})
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (u *MediaTaskUpsertBulk) SetUpstreamTaskID(v string) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetUpstreamTaskID(v)
	})
}

// UpdateUpstreamTaskID sets the "upstream_task_id" field to the value that was provided on create.
func (u *MediaTaskUpsertBulk) UpdateUpstreamTaskID() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateUpstreamTaskID()
	})
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (u *MediaTaskUpsertBulk) ClearUpstreamTaskID() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.ClearUpstreamTaskID()
	})
}

// SetStatus sets the "status" field.
func (u *MediaTaskUpsertBulk) SetStatus(v string) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MediaTaskUpsertBulk) UpdateStatus() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetResolution sets the "resolution" field.
func (u *MediaTaskUpsertBulk) SetResolution(v string) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetResolution(v)
	})
}

// UpdateResolution sets the "resolution" field to the value that was provided on create.
func (u *MediaTaskUpsertBulk) UpdateResolution() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateResolution()
	})
}

// ClearResolution clears the value of the "resolution" field.
func (u *MediaTaskUpsertBulk) ClearResolution() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.ClearResolution()
	})
}

// SetDurationSec sets the "duration_sec" field.
func (u *MediaTaskUpsertBulk) SetDurationSec(v int) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetDurationSec(v)
	})
}

// AddDurationSec adds v to the "duration_sec" field.
func (u *MediaTaskUpsertBulk) AddDurationSec(v int) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.AddDurationSec(v)
	})
}

// UpdateDurationSec sets the "duration_sec" field to the value that was provided on create.
func (u *MediaTaskUpsertBulk) UpdateDurationSec() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateDurationSec()
	})
}

// ClearDurationSec clears the value of the "duration_sec" field.
func (u *MediaTaskUpsertBulk) ClearDurationSec() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.ClearDurationSec()
	})
}

// SetMediaURL sets the "media_url" field.
func (u *MediaTaskUpsertBulk) SetMediaURL(v string) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetMediaURL(v)
	})
}

// UpdateMediaURL sets the "media_url" field to the value that was provided on create.
func (u *MediaTaskUpsertBulk) UpdateMediaURL() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateMediaURL()
	})
}

// ClearMediaURL clears the value of the "media_url" field.
func (u *MediaTaskUpsertBulk) ClearMediaURL() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.ClearMediaURL()
	})
}

// SetMediaUrls sets the "media_urls" field.
func (u *MediaTaskUpsertBulk) SetMediaUrls(v []string) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetMediaUrls(v)
	})
}

// UpdateMediaUrls sets the "media_urls" field to the value that was provided on create.
func (u *MediaTaskUpsertBulk) UpdateMediaUrls() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateMediaUrls()
	})
}

// ClearMediaUrls clears the value of the "media_urls" field.
func (u *MediaTaskUpsertBulk) ClearMediaUrls() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.ClearMediaUrls()
	})
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (u *MediaTaskUpsertBulk) SetThumbnailURL(v string) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetThumbnailURL(v)
	})
}

// UpdateThumbnailURL sets the "thumbnail_url" field to the value that was provided on create.
func (u *MediaTaskUpsertBulk) UpdateThumbnailURL() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateThumbnailURL()
	})
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (u *MediaTaskUpsertBulk) ClearThumbnailURL() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.ClearThumbnailURL()
	})
}

// SetRequestBody sets the "request_body" field.
func (u *MediaTaskUpsertBulk) SetRequestBody(v map[string]interface{}) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetRequestBody(v)
	})
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *MediaTaskUpsertBulk) UpdateRequestBody() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateRequestBody()
	})
}

// ClearRequestBody clears the value of the "request_body" field.
func (u *MediaTaskUpsertBulk) ClearRequestBody() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.ClearRequestBody()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *MediaTaskUpsertBulk) SetErrorMessage(v string) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *MediaTaskUpsertBulk) UpdateErrorMessage() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *MediaTaskUpsertBulk) ClearErrorMessage() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.ClearErrorMessage()
	})
}

// SetCostUsd sets the "cost_usd" field.
func (u *MediaTaskUpsertBulk) SetCostUsd(v float64) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetCostUsd(v)
	})
}

// AddCostUsd adds v to the "cost_usd" field.
func (u *MediaTaskUpsertBulk) AddCostUsd(v float64) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.AddCostUsd(v)
	})
}

// UpdateCostUsd sets the "cost_usd" field to the value that was provided on create.
func (u *MediaTaskUpsertBulk) UpdateCostUsd() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateCostUsd()
	})
}

// SetReservedCost sets the "reserved_cost" field.
func (u *MediaTaskUpsertBulk) SetReservedCost(v float64) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetReservedCost(v)
	})
}

// AddReservedCost adds v to the "reserved_cost" field.
func (u *MediaTaskUpsertBulk) AddReservedCost(v float64) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.AddReservedCost(v)
	})
}

// UpdateReservedCost sets the "reserved_cost" field to the value that was provided on create.
func (u *MediaTaskUpsertBulk) UpdateReservedCost() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateReservedCost()
	})
}

// ClearReservedCost clears the value of the "reserved_cost" field.
func (u *MediaTaskUpsertBulk) ClearReservedCost() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.ClearReservedCost()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *MediaTaskUpsertBulk) SetFinishedAt(v time.Time) *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *MediaTaskUpsertBulk) UpdateFinishedAt() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *MediaTaskUpsertBulk) ClearFinishedAt() *MediaTaskUpsertBulk {
	return u.Update(func(s *MediaTaskUpsert) {
		s.ClearFinishedAt()
	})
}

// Exec executes the query.
func (u *MediaTaskUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MediaTaskCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MediaTaskCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MediaTaskUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
