// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/mediatask"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// MediaTaskUpdate is the builder for updating MediaTask entities.
type MediaTaskUpdate struct {
	config
	hooks    []Hook
	mutation *MediaTaskMutation
}

// Where appends a list predicates to the MediaTaskUpdate builder.
func (_u *MediaTaskUpdate) Where(ps ...predicate.MediaTask) *MediaTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaTaskUpdate) SetUpdatedAt(v time.Time) *MediaTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLocalID sets the "local_id" field.
func (_u *MediaTaskUpdate) SetLocalID(v string) *MediaTaskUpdate {
	_u.mutation.SetLocalID(v)
	return _u
}

// SetNillableLocalID sets the "local_id" field if the given value is not nil.
func (_u *MediaTaskUpdate) SetNillableLocalID(v *string) *MediaTaskUpdate {
	if v != nil {
		_u.SetLocalID(*v)
	}
	return _u
}

// SetMediaKind sets the "media_kind" field.
func (_u *MediaTaskUpdate) SetMediaKind(v string) *MediaTaskUpdate {
	_u.mutation.SetMediaKind(v)
	return _u
}

// SetNillableMediaKind sets the "media_kind" field if the given value is not nil.
func (_u *MediaTaskUpdate) SetNillableMediaKind(v *string) *MediaTaskUpdate {
	if v != nil {
		_u.SetMediaKind(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MediaTaskUpdate) SetUserID(v int64) *MediaTaskUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MediaTaskUpdate) SetNillableUserID(v *int64) *MediaTaskUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *MediaTaskUpdate) AddUserID(v int64) *MediaTaskUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *MediaTaskUpdate) SetAPIKeyID(v int64) *MediaTaskUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *MediaTaskUpdate) SetNillableAPIKeyID(v *int64) *MediaTaskUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *MediaTaskUpdate) AddAPIKeyID(v int64) *MediaTaskUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *MediaTaskUpdate) ClearAPIKeyID() *MediaTaskUpdate {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetPublicModel sets the "public_model" field.
func (_u *MediaTaskUpdate) SetPublicModel(v string) *MediaTaskUpdate {
	_u.mutation.SetPublicModel(v)
	return _u
}

// SetNillablePublicModel sets the "public_model" field if the given value is not nil.
func (_u *MediaTaskUpdate) SetNillablePublicModel(v *string) *MediaTaskUpdate {
	if v != nil {
		_u.SetPublicModel(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *MediaTaskUpdate) SetUpstreamModel(v string) *MediaTaskUpdate {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *MediaTaskUpdate) SetNillableUpstreamModel(v *string) *MediaTaskUpdate {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *MediaTaskUpdate) SetAccountID(v int64) *MediaTaskUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *MediaTaskUpdate) SetNillableAccountID(v *int64) *MediaTaskUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *MediaTaskUpdate) AddAccountID(v int64) *MediaTaskUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_u *MediaTaskUpdate) SetUpstreamTaskID(v string) *MediaTaskUpdate {
	_u.mutation.SetUpstreamTaskID(v)
	return _u
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_u *MediaTaskUpdate) SetNillableUpstreamTaskID(v *string) *MediaTaskUpdate {
	if v != nil {
		_u.SetUpstreamTaskID(*v)
	}
	return _u
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (_u *MediaTaskUpdate) ClearUpstreamTaskID() *MediaTaskUpdate {
	_u.mutation.ClearUpstreamTaskID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *MediaTaskUpdate) SetStatus(v string) *MediaTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MediaTaskUpdate) SetNillableStatus(v *string) *MediaTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetResolution sets the "resolution" field.
func (_u *MediaTaskUpdate) SetResolution(v string) *MediaTaskUpdate {
	_u.mutation.SetResolution(v)
	return _u
}

// SetNillableResolution sets the "resolution" field if the given value is not nil.
func (_u *MediaTaskUpdate) SetNillableResolution(v *string) *MediaTaskUpdate {
	if v != nil {
		_u.SetResolution(*v)
	}
	return _u
}

// ClearResolution clears the value of the "resolution" field.
func (_u *MediaTaskUpdate) ClearResolution() *MediaTaskUpdate {
	_u.mutation.ClearResolution()
	return _u
}

// SetDurationSec sets the "duration_sec" field.
func (_u *MediaTaskUpdate) SetDurationSec(v int) *MediaTaskUpdate {
	_u.mutation.ResetDurationSec()
	_u.mutation.SetDurationSec(v)
	return _u
}

// SetNillableDurationSec sets the "duration_sec" field if the given value is not nil.
func (_u *MediaTaskUpdate) SetNillableDurationSec(v *int) *MediaTaskUpdate {
	if v != nil {
		_u.SetDurationSec(*v)
	}
	return _u
}

// AddDurationSec adds value to the "duration_sec" field.
func (_u *MediaTaskUpdate) AddDurationSec(v int) *MediaTaskUpdate {
	_u.mutation.AddDurationSec(v)
	return _u
}

// ClearDurationSec clears the value of the "duration_sec" field.
func (_u *MediaTaskUpdate) ClearDurationSec() *MediaTaskUpdate {
	_u.mutation.ClearDurationSec()
	return _u
}

// SetMediaURL sets the "media_url" field.
func (_u *MediaTaskUpdate) SetMediaURL(v string) *MediaTaskUpdate {
	_u.mutation.SetMediaURL(v)
	return _u
}

// SetNillableMediaURL sets the "media_url" field if the given value is not nil.
func (_u *MediaTaskUpdate) SetNillableMediaURL(v *string) *MediaTaskUpdate {
	if v != nil {
		_u.SetMediaURL(*v)
	}
	return _u
}

// ClearMediaURL clears the value of the "media_url" field.
func (_u *MediaTaskUpdate) ClearMediaURL() *MediaTaskUpdate {
	_u.mutation.ClearMediaURL()
	return _u
}

// SetMediaUrls sets the "media_urls" field.
func (_u *MediaTaskUpdate) SetMediaUrls(v []string) *MediaTaskUpdate {
	_u.mutation.SetMediaUrls(v)
	return _u
}

// AppendMediaUrls appends value to the "media_urls" field.
func (_u *MediaTaskUpdate) AppendMediaUrls(v []string) *MediaTaskUpdate {
	_u.mutation.AppendMediaUrls(v)
	return _u
}

// ClearMediaUrls clears the value of the "media_urls" field.
func (_u *MediaTaskUpdate) ClearMediaUrls() *MediaTaskUpdate {
	_u.mutation.ClearMediaUrls()
	return _u
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_u *MediaTaskUpdate) SetThumbnailURL(v string) *MediaTaskUpdate {
	_u.mutation.SetThumbnailURL(v)
	return _u
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_u *MediaTaskUpdate) SetNillableThumbnailURL(v *string) *MediaTaskUpdate {
	if v != nil {
		_u.SetThumbnailURL(*v)
	}
	return _u
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (_u *MediaTaskUpdate) ClearThumbnailURL() *MediaTaskUpdate {
	_u.mutation.ClearThumbnailURL()
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *MediaTaskUpdate) SetRequestBody(v map[string]interface{}) *MediaTaskUpdate {
	_u.mutation.SetRequestBody(v)
	return _u
}

// ClearRequestBody clears the value of the "request_body" field.
func (_u *MediaTaskUpdate) ClearRequestBody() *MediaTaskUpdate {
	_u.mutation.ClearRequestBody()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *MediaTaskUpdate) SetErrorMessage(v string) *MediaTaskUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *MediaTaskUpdate) SetNillableErrorMessage(v *string) *MediaTaskUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *MediaTaskUpdate) ClearErrorMessage() *MediaTaskUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetCostUsd sets the "cost_usd" field.
func (_u *MediaTaskUpdate) SetCostUsd(v float64) *MediaTaskUpdate {
	_u.mutation.ResetCostUsd()
	_u.mutation.SetCostUsd(v)
	return _u
}

// SetNillableCostUsd sets the "cost_usd" field if the given value is not nil.
func (_u *MediaTaskUpdate) SetNillableCostUsd(v *float64) *MediaTaskUpdate {
	if v != nil {
		_u.SetCostUsd(*v)
	}
	return _u
}

// AddCostUsd adds value to the "cost_usd" field.
func (_u *MediaTaskUpdate) AddCostUsd(v float64) *MediaTaskUpdate {
	_u.mutation.AddCostUsd(v)
	return _u
}

// SetReservedCost sets the "reserved_cost" field.
func (_u *MediaTaskUpdate) SetReservedCost(v float64) *MediaTaskUpdate {
	_u.mutation.ResetReservedCost()
	_u.mutation.SetReservedCost(v)
	return _u
}

// SetNillableReservedCost sets the "reserved_cost" field if the given value is not nil.
func (_u *MediaTaskUpdate) SetNillableReservedCost(v *float64) *MediaTaskUpdate {
	if v != nil {
		_u.SetReservedCost(*v)
	}
	return _u
}

// AddReservedCost adds value to the "reserved_cost" field.
func (_u *MediaTaskUpdate) AddReservedCost(v float64) *MediaTaskUpdate {
	_u.mutation.AddReservedCost(v)
	return _u
}

// ClearReservedCost clears the value of the "reserved_cost" field.
func (_u *MediaTaskUpdate) ClearReservedCost() *MediaTaskUpdate {
	_u.mutation.ClearReservedCost()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *MediaTaskUpdate) SetFinishedAt(v time.Time) *MediaTaskUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *MediaTaskUpdate) SetNillableFinishedAt(v *time.Time) *MediaTaskUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *MediaTaskUpdate) ClearFinishedAt() *MediaTaskUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the MediaTaskMutation object of the builder.
func (_u *MediaTaskUpdate) Mutation() *MediaTaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MediaTaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MediaTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaTaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mediatask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaTaskUpdate) check() error {
	if v, ok := _u.mutation.LocalID(); ok {
		if err := mediatask.LocalIDValidator(v); err != nil {
			return &ValidationError{Name: "local_id", err: fmt.Errorf(`ent: validator failed for field "MediaTask.local_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MediaKind(); ok {
		if err := mediatask.MediaKindValidator(v); err != nil {
			return &ValidationError{Name: "media_kind", err: fmt.Errorf(`ent: validator failed for field "MediaTask.media_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := mediatask.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "MediaTask.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKeyID(); ok {
		if err := mediatask.APIKeyIDValidator(v); err != nil {
			return &ValidationError{Name: "api_key_id", err: fmt.Errorf(`ent: validator failed for field "MediaTask.api_key_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicModel(); ok {
		if err := mediatask.PublicModelValidator(v); err != nil {
			return &ValidationError{Name: "public_model", err: fmt.Errorf(`ent: validator failed for field "MediaTask.public_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := mediatask.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "MediaTask.upstream_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountID(); ok {
		if err := mediatask.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "MediaTask.account_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamTaskID(); ok {
		if err := mediatask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "MediaTask.upstream_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := mediatask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MediaTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Resolution(); ok {
		if err := mediatask.ResolutionValidator(v); err != nil {
			return &ValidationError{Name: "resolution", err: fmt.Errorf(`ent: validator failed for field "MediaTask.resolution": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationSec(); ok {
		if err := mediatask.DurationSecValidator(v); err != nil {
			return &ValidationError{Name: "duration_sec", err: fmt.Errorf(`ent: validator failed for field "MediaTask.duration_sec": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediatask.Table, mediatask.Columns, sqlgraph.NewFieldSpec(mediatask.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mediatask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LocalID(); ok {
		_spec.SetField(mediatask.FieldLocalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MediaKind(); ok {
		_spec.SetField(mediatask.FieldMediaKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(mediatask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(mediatask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(mediatask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(mediatask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(mediatask.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.PublicModel(); ok {
		_spec.SetField(mediatask.FieldPublicModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(mediatask.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(mediatask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(mediatask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpstreamTaskID(); ok {
		_spec.SetField(mediatask.FieldUpstreamTaskID, field.TypeString, value)
	}
	if _u.mutation.UpstreamTaskIDCleared() {
		_spec.ClearField(mediatask.FieldUpstreamTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mediatask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Resolution(); ok {
		_spec.SetField(mediatask.FieldResolution, field.TypeString, value)
	}
	if _u.mutation.ResolutionCleared() {
		_spec.ClearField(mediatask.FieldResolution, field.TypeString)
	}
	if value, ok := _u.mutation.DurationSec(); ok {
		_spec.SetField(mediatask.FieldDurationSec, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationSec(); ok {
		_spec.AddField(mediatask.FieldDurationSec, field.TypeInt, value)
	}
	if _u.mutation.DurationSecCleared() {
		_spec.ClearField(mediatask.FieldDurationSec, field.TypeInt)
	}
	if value, ok := _u.mutation.MediaURL(); ok {
		_spec.SetField(mediatask.FieldMediaURL, field.TypeString, value)
	}
	if _u.mutation.MediaURLCleared() {
		_spec.ClearField(mediatask.FieldMediaURL, field.TypeString)
	}
	if value, ok := _u.mutation.MediaUrls(); ok {
		_spec.SetField(mediatask.FieldMediaUrls, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMediaUrls(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediatask.FieldMediaUrls, value)
		})
	}
	if _u.mutation.MediaUrlsCleared() {
		_spec.ClearField(mediatask.FieldMediaUrls, field.TypeJSON)
	}
	if value, ok := _u.mutation.ThumbnailURL(); ok {
		_spec.SetField(mediatask.FieldThumbnailURL, field.TypeString, value)
	}
	if _u.mutation.ThumbnailURLCleared() {
		_spec.ClearField(mediatask.FieldThumbnailURL, field.TypeString)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(mediatask.FieldRequestBody, field.TypeJSON, value)
	}
	if _u.mutation.RequestBodyCleared() {
		_spec.ClearField(mediatask.FieldRequestBody, field.TypeJSON)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(mediatask.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(mediatask.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.CostUsd(); ok {
		_spec.SetField(mediatask.FieldCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostUsd(); ok {
		_spec.AddField(mediatask.FieldCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ReservedCost(); ok {
		_spec.SetField(mediatask.FieldReservedCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedReservedCost(); ok {
		_spec.AddField(mediatask.FieldReservedCost, field.TypeFloat64, value)
	}
	if _u.mutation.ReservedCostCleared() {
		_spec.ClearField(mediatask.FieldReservedCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(mediatask.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(mediatask.FieldFinishedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediatask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MediaTaskUpdateOne is the builder for updating a single MediaTask entity.
type MediaTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaTaskMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaTaskUpdateOne) SetUpdatedAt(v time.Time) *MediaTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLocalID sets the "local_id" field.
func (_u *MediaTaskUpdateOne) SetLocalID(v string) *MediaTaskUpdateOne {
	_u.mutation.SetLocalID(v)
	return _u
}

// SetNillableLocalID sets the "local_id" field if the given value is not nil.
func (_u *MediaTaskUpdateOne) SetNillableLocalID(v *string) *MediaTaskUpdateOne {
	if v != nil {
		_u.SetLocalID(*v)
	}
	return _u
}

// SetMediaKind sets the "media_kind" field.
func (_u *MediaTaskUpdateOne) SetMediaKind(v string) *MediaTaskUpdateOne {
	_u.mutation.SetMediaKind(v)
	return _u
}

// SetNillableMediaKind sets the "media_kind" field if the given value is not nil.
func (_u *MediaTaskUpdateOne) SetNillableMediaKind(v *string) *MediaTaskUpdateOne {
	if v != nil {
		_u.SetMediaKind(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MediaTaskUpdateOne) SetUserID(v int64) *MediaTaskUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MediaTaskUpdateOne) SetNillableUserID(v *int64) *MediaTaskUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *MediaTaskUpdateOne) AddUserID(v int64) *MediaTaskUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *MediaTaskUpdateOne) SetAPIKeyID(v int64) *MediaTaskUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *MediaTaskUpdateOne) SetNillableAPIKeyID(v *int64) *MediaTaskUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *MediaTaskUpdateOne) AddAPIKeyID(v int64) *MediaTaskUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *MediaTaskUpdateOne) ClearAPIKeyID() *MediaTaskUpdateOne {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetPublicModel sets the "public_model" field.
func (_u *MediaTaskUpdateOne) SetPublicModel(v string) *MediaTaskUpdateOne {
	_u.mutation.SetPublicModel(v)
	return _u
}

// SetNillablePublicModel sets the "public_model" field if the given value is not nil.
func (_u *MediaTaskUpdateOne) SetNillablePublicModel(v *string) *MediaTaskUpdateOne {
	if v != nil {
		_u.SetPublicModel(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *MediaTaskUpdateOne) SetUpstreamModel(v string) *MediaTaskUpdateOne {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *MediaTaskUpdateOne) SetNillableUpstreamModel(v *string) *MediaTaskUpdateOne {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *MediaTaskUpdateOne) SetAccountID(v int64) *MediaTaskUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *MediaTaskUpdateOne) SetNillableAccountID(v *int64) *MediaTaskUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *MediaTaskUpdateOne) AddAccountID(v int64) *MediaTaskUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_u *MediaTaskUpdateOne) SetUpstreamTaskID(v string) *MediaTaskUpdateOne {
	_u.mutation.SetUpstreamTaskID(v)
	return _u
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_u *MediaTaskUpdateOne) SetNillableUpstreamTaskID(v *string) *MediaTaskUpdateOne {
	if v != nil {
		_u.SetUpstreamTaskID(*v)
	}
	return _u
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (_u *MediaTaskUpdateOne) ClearUpstreamTaskID() *MediaTaskUpdateOne {
	_u.mutation.ClearUpstreamTaskID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *MediaTaskUpdateOne) SetStatus(v string) *MediaTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MediaTaskUpdateOne) SetNillableStatus(v *string) *MediaTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetResolution sets the "resolution" field.
func (_u *MediaTaskUpdateOne) SetResolution(v string) *MediaTaskUpdateOne {
	_u.mutation.SetResolution(v)
	return _u
}

// SetNillableResolution sets the "resolution" field if the given value is not nil.
func (_u *MediaTaskUpdateOne) SetNillableResolution(v *string) *MediaTaskUpdateOne {
	if v != nil {
		_u.SetResolution(*v)
	}
	return _u
}

// ClearResolution clears the value of the "resolution" field.
func (_u *MediaTaskUpdateOne) ClearResolution() *MediaTaskUpdateOne {
	_u.mutation.ClearResolution()
	return _u
}

// SetDurationSec sets the "duration_sec" field.
func (_u *MediaTaskUpdateOne) SetDurationSec(v int) *MediaTaskUpdateOne {
	_u.mutation.ResetDurationSec()
	_u.mutation.SetDurationSec(v)
	return _u
}

// SetNillableDurationSec sets the "duration_sec" field if the given value is not nil.
func (_u *MediaTaskUpdateOne) SetNillableDurationSec(v *int) *MediaTaskUpdateOne {
	if v != nil {
		_u.SetDurationSec(*v)
	}
	return _u
}

// AddDurationSec adds value to the "duration_sec" field.
func (_u *MediaTaskUpdateOne) AddDurationSec(v int) *MediaTaskUpdateOne {
	_u.mutation.AddDurationSec(v)
	return _u
}

// ClearDurationSec clears the value of the "duration_sec" field.
func (_u *MediaTaskUpdateOne) ClearDurationSec() *MediaTaskUpdateOne {
	_u.mutation.ClearDurationSec()
	return _u
}

// SetMediaURL sets the "media_url" field.
func (_u *MediaTaskUpdateOne) SetMediaURL(v string) *MediaTaskUpdateOne {
	_u.mutation.SetMediaURL(v)
	return _u
}

// SetNillableMediaURL sets the "media_url" field if the given value is not nil.
func (_u *MediaTaskUpdateOne) SetNillableMediaURL(v *string) *MediaTaskUpdateOne {
	if v != nil {
		_u.SetMediaURL(*v)
	}
	return _u
}

// ClearMediaURL clears the value of the "media_url" field.
func (_u *MediaTaskUpdateOne) ClearMediaURL() *MediaTaskUpdateOne {
	_u.mutation.ClearMediaURL()
	return _u
}

// SetMediaUrls sets the "media_urls" field.
func (_u *MediaTaskUpdateOne) SetMediaUrls(v []string) *MediaTaskUpdateOne {
	_u.mutation.SetMediaUrls(v)
	return _u
}

// AppendMediaUrls appends value to the "media_urls" field.
func (_u *MediaTaskUpdateOne) AppendMediaUrls(v []string) *MediaTaskUpdateOne {
	_u.mutation.AppendMediaUrls(v)
	return _u
}

// ClearMediaUrls clears the value of the "media_urls" field.
func (_u *MediaTaskUpdateOne) ClearMediaUrls() *MediaTaskUpdateOne {
	_u.mutation.ClearMediaUrls()
	return _u
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_u *MediaTaskUpdateOne) SetThumbnailURL(v string) *MediaTaskUpdateOne {
	_u.mutation.SetThumbnailURL(v)
	return _u
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_u *MediaTaskUpdateOne) SetNillableThumbnailURL(v *string) *MediaTaskUpdateOne {
	if v != nil {
		_u.SetThumbnailURL(*v)
	}
	return _u
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (_u *MediaTaskUpdateOne) ClearThumbnailURL() *MediaTaskUpdateOne {
	_u.mutation.ClearThumbnailURL()
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *MediaTaskUpdateOne) SetRequestBody(v map[string]interface{}) *MediaTaskUpdateOne {
	_u.mutation.SetRequestBody(v)
	return _u
}

// ClearRequestBody clears the value of the "request_body" field.
func (_u *MediaTaskUpdateOne) ClearRequestBody() *MediaTaskUpdateOne {
	_u.mutation.ClearRequestBody()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *MediaTaskUpdateOne) SetErrorMessage(v string) *MediaTaskUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *MediaTaskUpdateOne) SetNillableErrorMessage(v *string) *MediaTaskUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *MediaTaskUpdateOne) ClearErrorMessage() *MediaTaskUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetCostUsd sets the "cost_usd" field.
func (_u *MediaTaskUpdateOne) SetCostUsd(v float64) *MediaTaskUpdateOne {
	_u.mutation.ResetCostUsd()
	_u.mutation.SetCostUsd(v)
	return _u
}

// SetNillableCostUsd sets the "cost_usd" field if the given value is not nil.
func (_u *MediaTaskUpdateOne) SetNillableCostUsd(v *float64) *MediaTaskUpdateOne {
	if v != nil {
		_u.SetCostUsd(*v)
	}
	return _u
}

// AddCostUsd adds value to the "cost_usd" field.
func (_u *MediaTaskUpdateOne) AddCostUsd(v float64) *MediaTaskUpdateOne {
	_u.mutation.AddCostUsd(v)
	return _u
}

// SetReservedCost sets the "reserved_cost" field.
func (_u *MediaTaskUpdateOne) SetReservedCost(v float64) *MediaTaskUpdateOne {
	_u.mutation.ResetReservedCost()
	_u.mutation.SetReservedCost(v)
	return _u
}

// SetNillableReservedCost sets the "reserved_cost" field if the given value is not nil.
func (_u *MediaTaskUpdateOne) SetNillableReservedCost(v *float64) *MediaTaskUpdateOne {
	if v != nil {
		_u.SetReservedCost(*v)
	}
	return _u
}

// AddReservedCost adds value to the "reserved_cost" field.
func (_u *MediaTaskUpdateOne) AddReservedCost(v float64) *MediaTaskUpdateOne {
	_u.mutation.AddReservedCost(v)
	return _u
}

// ClearReservedCost clears the value of the "reserved_cost" field.
func (_u *MediaTaskUpdateOne) ClearReservedCost() *MediaTaskUpdateOne {
	_u.mutation.ClearReservedCost()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *MediaTaskUpdateOne) SetFinishedAt(v time.Time) *MediaTaskUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *MediaTaskUpdateOne) SetNillableFinishedAt(v *time.Time) *MediaTaskUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *MediaTaskUpdateOne) ClearFinishedAt() *MediaTaskUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the MediaTaskMutation object of the builder.
func (_u *MediaTaskUpdateOne) Mutation() *MediaTaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the MediaTaskUpdate builder.
func (_u *MediaTaskUpdateOne) Where(ps ...predicate.MediaTask) *MediaTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MediaTaskUpdateOne) Select(field string, fields ...string) *MediaTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MediaTask entity.
func (_u *MediaTaskUpdateOne) Save(ctx context.Context) (*MediaTask, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaTaskUpdateOne) SaveX(ctx context.Context) *MediaTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MediaTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaTaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mediatask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaTaskUpdateOne) check() error {
	if v, ok := _u.mutation.LocalID(); ok {
		if err := mediatask.LocalIDValidator(v); err != nil {
			return &ValidationError{Name: "local_id", err: fmt.Errorf(`ent: validator failed for field "MediaTask.local_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MediaKind(); ok {
		if err := mediatask.MediaKindValidator(v); err != nil {
			return &ValidationError{Name: "media_kind", err: fmt.Errorf(`ent: validator failed for field "MediaTask.media_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := mediatask.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "MediaTask.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKeyID(); ok {
		if err := mediatask.APIKeyIDValidator(v); err != nil {
			return &ValidationError{Name: "api_key_id", err: fmt.Errorf(`ent: validator failed for field "MediaTask.api_key_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicModel(); ok {
		if err := mediatask.PublicModelValidator(v); err != nil {
			return &ValidationError{Name: "public_model", err: fmt.Errorf(`ent: validator failed for field "MediaTask.public_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := mediatask.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "MediaTask.upstream_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountID(); ok {
		if err := mediatask.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "MediaTask.account_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamTaskID(); ok {
		if err := mediatask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "MediaTask.upstream_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := mediatask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MediaTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Resolution(); ok {
		if err := mediatask.ResolutionValidator(v); err != nil {
			return &ValidationError{Name: "resolution", err: fmt.Errorf(`ent: validator failed for field "MediaTask.resolution": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationSec(); ok {
		if err := mediatask.DurationSecValidator(v); err != nil {
			return &ValidationError{Name: "duration_sec", err: fmt.Errorf(`ent: validator failed for field "MediaTask.duration_sec": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaTaskUpdateOne) sqlSave(ctx context.Context) (_node *MediaTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediatask.Table, mediatask.Columns, sqlgraph.NewFieldSpec(mediatask.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MediaTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediatask.FieldID)
		for _, f := range fields {
			if !mediatask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mediatask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mediatask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LocalID(); ok {
		_spec.SetField(mediatask.FieldLocalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MediaKind(); ok {
		_spec.SetField(mediatask.FieldMediaKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(mediatask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(mediatask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(mediatask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(mediatask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(mediatask.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.PublicModel(); ok {
		_spec.SetField(mediatask.FieldPublicModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(mediatask.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(mediatask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(mediatask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpstreamTaskID(); ok {
		_spec.SetField(mediatask.FieldUpstreamTaskID, field.TypeString, value)
	}
	if _u.mutation.UpstreamTaskIDCleared() {
		_spec.ClearField(mediatask.FieldUpstreamTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mediatask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Resolution(); ok {
		_spec.SetField(mediatask.FieldResolution, field.TypeString, value)
	}
	if _u.mutation.ResolutionCleared() {
		_spec.ClearField(mediatask.FieldResolution, field.TypeString)
	}
	if value, ok := _u.mutation.DurationSec(); ok {
		_spec.SetField(mediatask.FieldDurationSec, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationSec(); ok {
		_spec.AddField(mediatask.FieldDurationSec, field.TypeInt, value)
	}
	if _u.mutation.DurationSecCleared() {
		_spec.ClearField(mediatask.FieldDurationSec, field.TypeInt)
	}
	if value, ok := _u.mutation.MediaURL(); ok {
		_spec.SetField(mediatask.FieldMediaURL, field.TypeString, value)
	}
	if _u.mutation.MediaURLCleared() {
		_spec.ClearField(mediatask.FieldMediaURL, field.TypeString)
	}
	if value, ok := _u.mutation.MediaUrls(); ok {
		_spec.SetField(mediatask.FieldMediaUrls, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMediaUrls(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediatask.FieldMediaUrls, value)
		})
	}
	if _u.mutation.MediaUrlsCleared() {
		_spec.ClearField(mediatask.FieldMediaUrls, field.TypeJSON)
	}
	if value, ok := _u.mutation.ThumbnailURL(); ok {
		_spec.SetField(mediatask.FieldThumbnailURL, field.TypeString, value)
	}
	if _u.mutation.ThumbnailURLCleared() {
		_spec.ClearField(mediatask.FieldThumbnailURL, field.TypeString)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(mediatask.FieldRequestBody, field.TypeJSON, value)
	}
	if _u.mutation.RequestBodyCleared() {
		_spec.ClearField(mediatask.FieldRequestBody, field.TypeJSON)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(mediatask.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(mediatask.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.CostUsd(); ok {
		_spec.SetField(mediatask.FieldCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostUsd(); ok {
		_spec.AddField(mediatask.FieldCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ReservedCost(); ok {
		_spec.SetField(mediatask.FieldReservedCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedReservedCost(); ok {
		_spec.AddField(mediatask.FieldReservedCost, field.TypeFloat64, value)
	}
	if _u.mutation.ReservedCostCleared() {
		_spec.ClearField(mediatask.FieldReservedCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(mediatask.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(mediatask.FieldFinishedAt, field.TypeTime)
	}
	_node = &MediaTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediatask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
