// Code generated by ent, DO NOT EDIT.

package ticketmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLTE(FieldID, id))
}

// TicketID applies equality check predicate on the "ticket_id" field. It's identical to TicketIDEQ.
func TicketID(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldTicketID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldUserID, v))
}

// AuthorType applies equality check predicate on the "author_type" field. It's identical to AuthorTypeEQ.
func AuthorType(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldAuthorType, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldContent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// TicketIDEQ applies the EQ predicate on the "ticket_id" field.
func TicketIDEQ(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldTicketID, v))
}

// TicketIDNEQ applies the NEQ predicate on the "ticket_id" field.
func TicketIDNEQ(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldTicketID, v))
}

// TicketIDIn applies the In predicate on the "ticket_id" field.
func TicketIDIn(vs ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldTicketID, vs...))
}

// TicketIDNotIn applies the NotIn predicate on the "ticket_id" field.
func TicketIDNotIn(vs ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldTicketID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotNull(FieldUserID))
}

// AuthorTypeEQ applies the EQ predicate on the "author_type" field.
func AuthorTypeEQ(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldAuthorType, v))
}

// AuthorTypeNEQ applies the NEQ predicate on the "author_type" field.
func AuthorTypeNEQ(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldAuthorType, v))
}

// AuthorTypeIn applies the In predicate on the "author_type" field.
func AuthorTypeIn(vs ...string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldAuthorType, vs...))
}

// AuthorTypeNotIn applies the NotIn predicate on the "author_type" field.
func AuthorTypeNotIn(vs ...string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldAuthorType, vs...))
}

// AuthorTypeGT applies the GT predicate on the "author_type" field.
func AuthorTypeGT(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGT(FieldAuthorType, v))
}

// AuthorTypeGTE applies the GTE predicate on the "author_type" field.
func AuthorTypeGTE(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGTE(FieldAuthorType, v))
}

// AuthorTypeLT applies the LT predicate on the "author_type" field.
func AuthorTypeLT(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLT(FieldAuthorType, v))
}

// AuthorTypeLTE applies the LTE predicate on the "author_type" field.
func AuthorTypeLTE(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLTE(FieldAuthorType, v))
}

// AuthorTypeContains applies the Contains predicate on the "author_type" field.
func AuthorTypeContains(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldContains(FieldAuthorType, v))
}

// AuthorTypeHasPrefix applies the HasPrefix predicate on the "author_type" field.
func AuthorTypeHasPrefix(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldHasPrefix(FieldAuthorType, v))
}

// AuthorTypeHasSuffix applies the HasSuffix predicate on the "author_type" field.
func AuthorTypeHasSuffix(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldHasSuffix(FieldAuthorType, v))
}

// AuthorTypeEqualFold applies the EqualFold predicate on the "author_type" field.
func AuthorTypeEqualFold(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEqualFold(FieldAuthorType, v))
}

// AuthorTypeContainsFold applies the ContainsFold predicate on the "author_type" field.
func AuthorTypeContainsFold(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldContainsFold(FieldAuthorType, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldContainsFold(FieldContent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTicket applies the HasEdge predicate on the "ticket" edge.
func HasTicket() predicate.TicketMessage {
	return predicate.TicketMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TicketTable, TicketColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTicketWith applies the HasEdge predicate on the "ticket" edge with a given conditions (other predicates).
func HasTicketWith(preds ...predicate.Ticket) predicate.TicketMessage {
	return predicate.TicketMessage(func(s *sql.Selector) {
		step := newTicketStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.TicketMessage {
	return predicate.TicketMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.TicketMessage {
	return predicate.TicketMessage(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TicketMessage) predicate.TicketMessage {
	return predicate.TicketMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TicketMessage) predicate.TicketMessage {
	return predicate.TicketMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TicketMessage) predicate.TicketMessage {
	return predicate.TicketMessage(sql.NotPredicates(p))
}
