// Code generated by ent, DO NOT EDIT.

package mediatask

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the mediatask type in the database.
	Label = "media_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldLocalID holds the string denoting the local_id field in the database.
	FieldLocalID = "local_id"
	// FieldMediaKind holds the string denoting the media_kind field in the database.
	FieldMediaKind = "media_kind"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldPublicModel holds the string denoting the public_model field in the database.
	FieldPublicModel = "public_model"
	// FieldUpstreamModel holds the string denoting the upstream_model field in the database.
	FieldUpstreamModel = "upstream_model"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldUpstreamTaskID holds the string denoting the upstream_task_id field in the database.
	FieldUpstreamTaskID = "upstream_task_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldResolution holds the string denoting the resolution field in the database.
	FieldResolution = "resolution"
	// FieldDurationSec holds the string denoting the duration_sec field in the database.
	FieldDurationSec = "duration_sec"
	// FieldMediaURL holds the string denoting the media_url field in the database.
	FieldMediaURL = "media_url"
	// FieldMediaUrls holds the string denoting the media_urls field in the database.
	FieldMediaUrls = "media_urls"
	// FieldThumbnailURL holds the string denoting the thumbnail_url field in the database.
	FieldThumbnailURL = "thumbnail_url"
	// FieldRequestBody holds the string denoting the request_body field in the database.
	FieldRequestBody = "request_body"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldCostUsd holds the string denoting the cost_usd field in the database.
	FieldCostUsd = "cost_usd"
	// FieldReservedCost holds the string denoting the reserved_cost field in the database.
	FieldReservedCost = "reserved_cost"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// Table holds the table name of the mediatask in the database.
	Table = "media_tasks"
)

// Columns holds all SQL columns for mediatask fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldLocalID,
	FieldMediaKind,
	FieldUserID,
	FieldAPIKeyID,
	FieldPublicModel,
	FieldUpstreamModel,
	FieldAccountID,
	FieldUpstreamTaskID,
	FieldStatus,
	FieldResolution,
	FieldDurationSec,
	FieldMediaURL,
	FieldMediaUrls,
	FieldThumbnailURL,
	FieldRequestBody,
	FieldErrorMessage,
	FieldCostUsd,
	FieldReservedCost,
	FieldFinishedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// LocalIDValidator is a validator for the "local_id" field. It is called by the builders before save.
	LocalIDValidator func(string) error
	// DefaultMediaKind holds the default value on creation for the "media_kind" field.
	DefaultMediaKind string
	// MediaKindValidator is a validator for the "media_kind" field. It is called by the builders before save.
	MediaKindValidator func(string) error
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(int64) error
	// APIKeyIDValidator is a validator for the "api_key_id" field. It is called by the builders before save.
	APIKeyIDValidator func(int64) error
	// PublicModelValidator is a validator for the "public_model" field. It is called by the builders before save.
	PublicModelValidator func(string) error
	// UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	UpstreamModelValidator func(string) error
	// AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	AccountIDValidator func(int64) error
	// UpstreamTaskIDValidator is a validator for the "upstream_task_id" field. It is called by the builders before save.
	UpstreamTaskIDValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// ResolutionValidator is a validator for the "resolution" field. It is called by the builders before save.
	ResolutionValidator func(string) error
	// DurationSecValidator is a validator for the "duration_sec" field. It is called by the builders before save.
	DurationSecValidator func(int) error
	// DefaultCostUsd holds the default value on creation for the "cost_usd" field.
	DefaultCostUsd float64
)

// OrderOption defines the ordering options for the MediaTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByLocalID orders the results by the local_id field.
func ByLocalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocalID, opts...).ToFunc()
}

// ByMediaKind orders the results by the media_kind field.
func ByMediaKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMediaKind, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByPublicModel orders the results by the public_model field.
func ByPublicModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicModel, opts...).ToFunc()
}

// ByUpstreamModel orders the results by the upstream_model field.
func ByUpstreamModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamModel, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByUpstreamTaskID orders the results by the upstream_task_id field.
func ByUpstreamTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamTaskID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByResolution orders the results by the resolution field.
func ByResolution(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolution, opts...).ToFunc()
}

// ByDurationSec orders the results by the duration_sec field.
func ByDurationSec(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationSec, opts...).ToFunc()
}

// ByMediaURL orders the results by the media_url field.
func ByMediaURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMediaURL, opts...).ToFunc()
}

// ByThumbnailURL orders the results by the thumbnail_url field.
func ByThumbnailURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThumbnailURL, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByCostUsd orders the results by the cost_usd field.
func ByCostUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostUsd, opts...).ToFunc()
}

// ByReservedCost orders the results by the reserved_cost field.
func ByReservedCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservedCost, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}
